disabled_rules:
  - multiple_closures_with_trailing_closure
  - leading_whitespace
  - trailing_whitespace
  - generic_type_name
  - identifier_name
  - opening_brace
  - vertical_whitespace
# - let_var_whitespace
# - implicitly_unwrapped_optional
opt_in_rules:
  - literal_expression_end_indentation
  - vertical_parameter_alignment_on_call
  - vertical_parameter_alignment
  - empty_count
  - array_init
#  - force_unwrapping
  - empty_parameters
  - closure_spacing
  - implicitly_unwrapped_optional
  - let_var_whitespace
  - overridden_super_call
  - weak_delegate
  - closing_brace
  - opening_brace
  - return_arrow_whitespace
  - trailing_semicolon
  - statement_position
  - syntactic_sugar
  - control_statement
  - trailing_newline
  - operator_usage_whitespace
  - yoda_condition
  - lower_acl_than_parent
  - redundant_type_annotation
  - unneeded_parentheses_in_closure_argument
  - attributes
#  - strict_fileprivate
#  - file_name
#  - trailing_closure
excluded:
- Carthage
- Pods
force_unwrapping: error
trailing_semicolon: error
empty_count: error
closing_brace: error
opening_brace: error
return_arrow_whitespace: error
statement_position: error
colon: error
comma: error
force_cast: error
force_try:
  severity: warning
line_length: 200
type_body_length:
  warning: 300
  error: 400
file_length:
  warning: 550
  error: 700
function_body_length:
  warning: 100
  error: 250
type_name:
  min_length: 1
  max_length:
    warning: 40
    error: 50
# warning_threshold: 15
reporter: "xcode"
# TODO Remove commented later
# identifier_name:
#   min_length: # only min_length
    # error: 2 # only error
